### ISSUE TITLE
Cannot rename default(?) group

### ISSUE THREAD

**Issue by BrightLight** [Soloplan/whatson#38] opened 2020-02-17 07:30 UTC
I added a bunch of "tool" projects using the wizard. As usual, all these new projects were put in a new, nameless group (btw: why don't you use the folder name from Jenkins? Or at least something like "New group (1)" or whatever?).
Of course I want to give this new group a meaningful name. However, when right-clicking on this nameless group, I don't get a context menu. All other groups have names and the context menu appears when right-clicking. But right-clicking on this nameless group doesn't give me the context menu, therefore I don't have the "Rename" option available.

![2020-02-17_whatson_NoContextMenu](https://user-images.githubusercontent.com/1859278/74632445-ac23ed00-515f-11ea-9369-a243c95f976e.png)

**Comment by steffen-wilke** [comment] 2020-02-17 08:07
Related (or even duplicate of) #35

**Comment by dominikgolda** [comment] 2020-02-18 14:22
The problem was the content of group row.  I think that the controls filled only part of the row and only this part supported context menu. I added a dummy item to fill the rest of the row and removed the minimal width of first panel.

**Closed as completed by dominikgolda** 2020-02-18 14:22 UTC
