### ISSUE TITLE
Projects that can't connect show last activity as 2020 years ago.

### ISSUE THREAD

**Issue by bytefluxio** [Soloplan/whatson#4] opened 2019-11-13 13:58 UTC
We have a build project that has been discontinued.
The last activity/update time shows 2020 years ago instead of mentioning that the connection couldn't be established.

I imagine, that projects that aren't discontinued, but just can't be connected to right now, might have the same issue.

![2019-11-13_14-55-07](https://user-images.githubusercontent.com/29196542/68770231-0f185c00-0626-11ea-96d7-59d7f7969c34.png)

**Comment by steffen-wilke** [comment] 2019-12-18 08:54
Possibly duplicate of #7

**Comment by steffen-wilke** [comment] 2020-01-13 10:02
Closing this as duplicate, in favor for #7

**Closed as completed by steffen-wilke** 2020-01-13 10:02 UTC
Labels: enhancement, Area: Main Window
